services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crud.settings
      - key: SECRET_KEY
        value: 'django-insecure-vpkxdmv8z0gl=^1&v$pye-1)@wa*63%tw-(l2@^hrmx7=&x5!7'
      - key: DEBUG
        value: False
